create table enOperacion (
	idVehiculoOperacion VARCHAR(50),
	modelo VARCHAR(6),
	ano VARCHAR(6),
	primary key (idVehiculoOperacion)
);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-379', 'Crossfire', 2008);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-148', 'RX', 2012);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-480', '8 Series', 1993);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-876', 'Neon', 1999);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-797', 'Sundance', 1994);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-612', 'Sorento', 2004);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-865', 'Mazda5', 2010);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-781', 'Swift', 1992);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-683', 'Sierra 3500', 2006);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-767', 'Town Car', 1994);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-019', 'Legend', 1987);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-168', 'Astro', 2003);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-873', 'Highlander', 2007);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-261', 'Sigma', 1990);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-004', 'Starion', 1988);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-724', 'Crossfire', 2006);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-037', 'Villager', 2001);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-711', '300CE', 1992);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-431', 'Volare', 1976);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-665', 'Bronco II', 1984);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-241', 'X5', 2012);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-668', 'Wrangler', 1994);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-852', 'Mustang', 2006);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-781', 'Charger', 2012);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-468', 'Highlander', 2007);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-660', 'Bronco II', 1986);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-697', 'H2 SUT', 2006);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-936', 'Jetta', 2009);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-863', 'Leone', 1989);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-734', 'Rally Wagon 2500', 1993);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-809', 'Jetta', 2009);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-771', '300', 2011);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-435', 'Legend', 1993);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-746', 'Starion', 1988);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-319', '9-5', 2011);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-059', 'Azure', 2009);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-307', 'Cougar', 1987);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-820', 'Sable', 1997);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-367', 'Jetta', 2009);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-881', 'H2', 2008);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-589', 745, 2002);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-005', 'Golf', 2003);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-271', 'Navigator', 2009);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-088', '300CE', 1992);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-098', 'Intrepid', 1998);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-408', 'Topaz', 1993);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-722', 'Corvette', 1989);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-445', 'Compass', 2012);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-330', 'Bronco II', 1986);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-253', 'Crossfire', 2006);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-861', 'Pacifica', 2004);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-367', 'Milan', 2006);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-044', 'Leone', 1989);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-189', 'Bronco II', 1984);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-086', 'California', 2009);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-031', 'Mustang', 2006);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-534', 'Navigator L', 2012);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-031', 'Tahoe', 2010);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-314', '911', 2008);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-698', 'Eclipse', 2002);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-098', 'Legend', 1987);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-176', '8 Series', 1993);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-708', 'Sierra 3500', 2006);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-359', 'Z3', 2001);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-486', 'Continental Mark VII', 1990);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-665', 'Rio', 2008);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-317', 'Taurus', 1999);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-928', 'California', 2009);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-642', 'LX', 2001);
insert into enOperacion (idVehiculoOperacion, modelo, ano) values ('o-722', 'Swift', 1992);
