create table vehiculo (
	modelo VARCHAR(50),
	ano VARCHAR(50),
	marca VARCHAR(50),
	refraccion VARCHAR(50),
	no_cilindros INT,
	no_puertas DECIMAL(10,2),
	primary key (modelo,ano)
);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Pathfinder', 2006, 'Nissan', true, 8, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Crown Victoria', 2001, 'Ford', false, 4, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Galant', 2008, 'Mitsubishi', true, 4, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('LX', 1998, 'Lexus', false, 1, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Murano', 2003, 'Nissan', false, 5, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Somerset', 1985, 'Buick', false, 4, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('CTS', 2003, 'Cadillac', true, 9, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Villager', 2002, 'Mercury', false, 1, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('MKX', 2010, 'Lincoln', true, 5, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('M6', 2009, 'BMW', true, 4, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('S60', 2005, 'Volvo', false, 8, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('LX', 2010, 'Lexus', false, 3, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('GT350', 1969, 'Shelby', true, 1, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('LaCrosse', 2009, 'Buick', true, 5, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Topaz', 1988, 'Mercury', true, 6, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Ram Van 2500', 2001, 'Dodge', true, 1, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Corvette', 2011, 'Chevrolet', true, 9, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('TrailBlazer', 2009, 'Chevrolet', false, 5, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Alcyone SVX', 1993, 'Subaru', false, 4, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Sparrow', 1999, 'Corbin', false, 2, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Paseo', 1993, 'Toyota', true, 8, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('E-Class', 2009, 'Mercedes-Benz', false, 4, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Oasis', 1998, 'Isuzu', true, 10, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Axiom', 2003, 'Isuzu', false, 8, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('V8', 1992, 'Audi', false, 5, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('M3', 1999, 'BMW', false, 2, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('LS', 2010, 'Lexus', false, 10, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('900', 1984, 'Saab', true, 4, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Range Rover', 2006, 'Land Rover', false, 5, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Altima', 2000, 'Nissan', false, 2, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('LX', 1999, 'Lexus', true, 2, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('3000GT', 1996, 'Mitsubishi', false, 10, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Camry', 1996, 'Toyota', true, 7, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('S80', 2006, 'Volvo', false, 4, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Daewoo Magnus', 2005, 'Suzuki', true, 5, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Cavalier', 2001, 'Chevrolet', false, 9, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Z3', 1997, 'BMW', true, 1, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('RL', 2011, 'Acura', false, 6, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Silverado', 2006, 'Chevrolet', false, 8, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Titan', 2008, 'Nissan', true, 8, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Elan', 1994, 'Lotus', false, 10, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Trans Sport', 1996, 'Pontiac', true, 4, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('QX', 2010, 'Infiniti', false, 6, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('LX', 2013, 'Lexus', false, 7, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Thunderbird', 1989, 'Ford', true, 5, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Celica', 1993, 'Toyota', true, 3, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('B-Series', 2004, 'Mazda', false, 7, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Explorer Sport', 2001, 'Ford', true, 10, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Safari', 1997, 'GMC', true, 9, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Ranger', 1997, 'Ford', true, 9, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Impala', 1996, 'Chevrolet', false, 10, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Aerostar', 1996, 'Ford', true, 5, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Bonneville', 1987, 'Pontiac', false, 7, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('98', 1994, 'Oldsmobile', false, 10, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Land Cruiser', 2002, 'Toyota', true, 7, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('GTI', 1985, 'Volkswagen', false, 2, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('G6', 2009, 'Pontiac', false, 10, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Dynasty', 1993, 'Dodge', true, 2, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Sierra 3500', 2006, 'GMC', true, 3, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Sable', 2009, 'Mercury', false, 7, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Passport', 1995, 'Honda', true, 3, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Sequoia', 2008, 'Toyota', true, 6, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('CTS-V', 2006, 'Cadillac', false, 9, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Sebring', 2000, 'Chrysler', true, 6, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Tahoe', 1999, 'Chevrolet', true, 1, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Accent', 2003, 'Hyundai', true, 3, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Suburban 2500', 1995, 'GMC', true, 5, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Acclaim', 1993, 'Plymouth', true, 1, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Sequoia', 2012, 'Toyota', false, 4, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('TT', 2009, 'Audi', true, 10, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Santa Fe', 2004, 'Hyundai', false, 9, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('RAV4', 2005, 'Toyota', true, 9, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Ipsum', 2000, 'Toyota', true, 10, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Celica', 1995, 'Toyota', false, 1, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('X6 M', 2013, 'BMW', true, 3, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Grand Marquis', 2005, 'Mercury', true, 7, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Optima', 2009, 'Kia', false, 9, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Savana Cargo Van', 2006, 'GMC', true, 6, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Riviera', 1995, 'Buick', false, 8, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Freestar', 2004, 'Ford', false, 4, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Explorer Sport Trac', 2001, 'Ford', false, 5, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Suburban 1500', 2003, 'Chevrolet', true, 2, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Trans Sport', 1998, 'Pontiac', true, 1, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Tracker', 1992, 'Geo', true, 2, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Ion', 2007, 'Saturn', true, 3, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('TL', 2008, 'Acura', false, 1, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('911', 2006, 'Porsche', true, 6, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Sonata', 2009, 'Hyundai', false, 1, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Astro', 2002, 'Chevrolet', false, 9, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('300ZX', 1992, 'Nissan', true, 10, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('CL-Class', 2002, 'Mercedes-Benz', false, 3, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Suburban 1500', 2009, 'Chevrolet', false, 6, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Avalon', 2006, 'Toyota', false, 5, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Aerio', 2007, 'Suzuki', false, 1, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Escalade EXT', 2008, 'Cadillac', false, 10, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('C-Class', 2010, 'Mercedes-Benz', true, 6, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('SSR', 2004, 'Chevrolet', false, 2, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('S6', 2011, 'Audi', false, 1, 4);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('Protege', 1997, 'Mazda', true, 6, 2);
insert into vehiculo (modelo, ano, marca, refraccion, no_cilindros, no_puertas) values ('R8', 2011, 'Audi', false, 2, 4);
